# Operaciones Matemáticas con NumPy — Cuaderno de Ejercicios
**Carrera:** Ciencia de Datos e Inteligencia Artificial  
**Asignatura:** Programación II  
**Fecha:** 2025-11-10

Este cuaderno contiene ejercicios prácticos basados en la presentación *"Mathematical Operations with NumPy"*.
> Objetivo: aplicar operaciones vectorizadas, funciones elementales, broadcasting, operaciones matriciales y estadísticas con NumPy.

---
**Instrucciones**
- Ejecuta las celdas en orden.
- Completa los `TODO`.
- No uses bucles `for` donde se solicite vectorización.
- Puedes usar `assert` para verificar tus resultados.


In [1]:
# Configuración básica
import numpy as np
import math

np.set_printoptions(precision=4, suppress=True)  # impresión amigable
print("NumPy versión:", np.__version__)


NumPy versión: 2.3.5


## 1) Operaciones aritméticas elementales (vectorización)
Trabaja con arrays y escalares. Evita bucles explícitos.


In [2]:
# Ejercicio 1.1: Suma, resta, multiplicación y división elemento a elemento
# Dados:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# TODO: calcula las cuatro operaciones en variables: suma, resta, mult, div
# (usa operadores vectorizados o funciones de NumPy)
suma = x+y      # TODO
resta = x-y     # TODO
mult = x*y      # TODO
div  = x/y      # TODO

# Verificación esperada (forma):
assert suma.shape == (2,2) and resta.shape == (2,2) and mult.shape == (2,2) and div.shape == (2,2)
suma, resta, mult, div

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2   , 0.3333],
        [0.4286, 0.5   ]]))

In [5]:
# Ejercicio 1.2: Operaciones in-place vs no in-place
# Copia de seguridad
z = x.copy()
w = x.copy()

# TODO: actualiza 'z' con suma in-place y 'w' con una nueva asignación
# Pista: in-place usa el operador '+='
z += w
w = w + z

# Imprime para comparar
print("z (in-place):\n", z)
print("w (nueva asignación):\n", w)

z (in-place):
 [[2 4]
 [6 8]]
w (nueva asignación):
 [[ 3  6]
 [ 9 12]]


## 2) Funciones matemáticas elementales
Aplica `np.sin`, `np.cos`, `np.tan`, `np.exp`, `np.sqrt`, `np.log`, `np.log10`, `np.log2` sobre datos.


In [9]:
# Ejercicio 2.1: tabla de funciones
x = np.linspace(-1, 1, 11)  # 11 valores equiespaciados
# TODO: calcula y_sin = sin(pi*x) redondeado a 4 decimales usando np.round
y_sin = np.round(np.sin(np.pi*x), 4)  # TODO

# TODO: calcula y_exp = exp(x), y_sqrt = sqrt(|x|), y_log = log(|x| + 1)
y_exp  = np.exp(x) # TODO
y_sqrt = np.sqrt(np.abs(x)) # TODO
y_log  = np.log(np.abs(x) + 1) # TODO

y_sin, y_exp[:3], y_sqrt[:3], y_log[:3]

(array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
         0.9511,  0.9511,  0.5878,  0.    ]),
 array([0.3679, 0.4493, 0.5488]),
 array([1.    , 0.8944, 0.7746]),
 array([0.6931, 0.5878, 0.47  ]))

## 3) Broadcasting
Combina arreglos de diferentes *shapes* respetando las reglas de broadcasting.


In [10]:
# Ejercicio 3.1: Vector fila + vector columna
a = np.array([1, 2, 3])        # shape (3,)
b = np.array([[10],[20],[30]]) # shape (3,1)

# TODO: usa broadcasting para obtener una matriz 3x3 donde C[i,j] = a[j] + b[i,0]
C = a+b  # TODO
assert C.shape == (3,3)
C

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [11]:
# Ejercicio 3.2: Normalización por columnas mediante broadcasting
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

# TODO: normaliza cada columna a [0,1] => (M - min_col) / (max_col - min_col)
min_col = M.min(axis=0)  # TODO (shape (3,) o (1,3))
max_col = M.max(axis=0)  # TODO
M_norm  = (M - min_col) / (max_col - min_col)  # TODO
M_norm

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [12]:
# Ejercicio 3.3: Broadcasting 3D
A = np.random.randint(0, 5, size=(2,3,1))
B = np.random.randint(0, 5, size=(1,1,4))

# TODO: calcula S = A + B utilizando broadcasting; verifica su shape
S = A + B  # TODO
assert S.shape == (2,3,4)
S.shape

(2, 3, 4)

## 4) Operaciones vectoriales y matriciales
Usa `np.dot`, `@`, `np.inner`, `np.outer`, `np.cross`.


In [13]:
# Ejercicio 4.1: Producto punto y matriz
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
A = np.arange(1, 10).reshape(3, 3)

# TODO: dot_uv = u·v ; AB = A @ A.T
dot_uv = u*v   # TODO
AB = A@A.T       # TODO

dot_uv, AB

(array([ 4, 10, 18]),
 array([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]]))

In [14]:
# Ejercicio 4.2: Producto externo y producto cruz
# TODO: calcula outer_uv = np.outer(u, v) y cross_uv = np.cross(u, v)
outer_uv = np.outer(u, v) # TODO
cross_uv = np.cross(u, v) # TODO
outer_uv, cross_uv

(array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]),
 array([-3,  6, -3]))

## 5) Estadística descriptiva
Trabaja con `np.mean`, `np.median`, `np.var`, `np.std`, `ddof`.


In [18]:
# Ejercicio 5.1: Descriptivos
data = np.array([3.5, 1.1, 3.2, 2.8, 6.7, 4.4, 0.9, 2.2])

# TODO: calcula media, mediana, varianza y desviación estándar poblacionales
media   = np.mean(data)  # TODO
mediana = np.median(data)  # TODO
var_p   = np.var(data)  # TODO
std_p   = np.std(data)  # TODO

# TODO: calcula varianza y desviación estándar muestrales (ddof=1)
var_m = np.var(data, ddof=1)    # TODO
std_m = np.std(data, ddof=1)    # TODO

(media, mediana, var_p, std_p, var_m, std_m)

(np.float64(3.1),
 np.float64(3.0),
 np.float64(3.0700000000000007),
 np.float64(1.7521415467935233),
 np.float64(3.5085714285714293),
 np.float64(1.8731181032095732))

## 6) Mini-proyecto (integración de conceptos)
**Objetivo:** Dado un vector `x` con ruido, genera:
1. `x_norm`: normalización min-max de `x`.
2. `mov3`: promedio móvil con ventana 3 (usar `np.convolve`).
3. `z`: estandarización z-score.
4. Verifica que `z` tiene media ≈ 0 y desviación estándar ≈ 1 (usa `assert`).

> No uses bucles explícitos.


In [19]:
# Datos de ejemplo (modifica si lo deseas)
rng = np.random.default_rng(42)
x = rng.normal(loc=10, scale=3, size=30)

# TODO 1: normalización min-max
x_norm =  (x - x.min()) / (x.max() - x.min())  # TODO

# TODO 2: promedio móvil con ventana 3 (modo 'valid')
mov3 = np.convolve(x, np.ones(3)/3, mode='valid')     # TODO

# TODO 3: z-score
z = (x - x.mean()) / x.std()        # TODO

# TODO 4: verificaciones aproximadas
assert abs(z.mean()) < 1e-12 or round(z.mean(), 12) == 0
assert abs(z.std() - 1) < 1e-9

x[:5], x_norm[:5], mov3[:5], z[:5]

(array([10.9142,  6.88  , 12.2514, 12.8217,  4.1469]),
 array([0.7108, 0.2871, 0.8512, 0.9111, 0.    ]),
 array([10.0152, 10.651 ,  9.74  ,  7.6874,  6.8746]),
 array([ 0.377 , -1.3838,  0.9606,  1.2096, -2.5768]))

<details>
<summary><strong>Mostrar soluciones (opcional)</strong></summary>

### Soluciones sugeridas (haz clic para desplegar)
**1.1** `x + y`, `x - y`, `x * y`, `y / x`  
**1.2** `z += y` y `w = w + y`  
**2.1** `np.round(np.sin(np.pi*x), 4)`, `np.exp(x)`, `np.sqrt(np.abs(x))`, `np.log(np.abs(x) + 1)`  
**3.1** `C = a + b`  
**3.2** `min_col = M.min(axis=0, keepdims=True)`, `max_col = M.max(axis=0, keepdims=True)`, `M_norm = (M-min_col)/(max_col-min_col)`  
**3.3** `S = A + B`  
**4.1** `dot_uv = np.dot(u, v)`, `AB = A @ A.T`  
**4.2** `outer_uv = np.outer(u, v)`, `cross_uv = np.cross(u, v)`  
**5.1** `np.mean`, `np.median`, `np.var`, `np.std`, y con `ddof=1` para muestral  
**6** ver fórmulas del enunciado
</details>
