# NumPy — Unidad 2 Semana 1: Notebook de ejercicios
**Fecha:** 2025-11-05

Este cuaderno contiene ejercicios prácticos para acompañar las diapositivas de **Fundamentos de NumPy y Arreglos Numéricos**.

**Temas:** instalación y verificación, creación de arreglos 1D/2D/3D, propiedades (`dtype`, `shape`, `ndim`), operaciones básicas, estadísticas simples, `reshape`/`flatten`, indexación y slicing.

> Sugerencia: intenta cada ejercicio **sin** ver la solución. Luego compara con la sección de **Soluciones** al final.

## 0. Preparación del entorno

In [1]:
# Si estás en Google Colab o Anaconda, NumPy ya está disponible.
# Si fuese necesario (entornos locales), descomenta la siguiente línea:
# !pip install numpy

import numpy as np
print('Versión de NumPy:', np.__version__)


Versión de NumPy: 2.3.5


## 1. Arreglos unidimensionales (1D)
**Objetivo:** crear vectores con distintos métodos y explorar sus propiedades.

**Ejercicio 1.1** → Crea un arreglo `a` con los valores `[1, 2, 3, 4, 5]` usando `np.array`. Luego imprime su `dtype`, `shape` y `ndim`.

In [2]:
# Tu código aquí
a = np.array([1, 2, 3, 4, 5])
print(a.dtype, a.shape, a.ndim)


int64 (5,) 1


**Ejercicio 1.2** → Crea un vector de ceros de tamaño 8 y otro de unos de tamaño 5. Usa `np.zeros` y `np.ones`.

In [4]:
# Tu código aquí
z = np.zeros(8)
o = np.ones(5)
z, o



(array([0., 0., 0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

**Ejercicio 1.3** → Genera un vector con números pares del 0 al 20 **incluido** usando `np.arange`. Luego calcula su suma con `np.sum`.

In [9]:
# Tu código aquí
v = np.arange(0, 21, 2)
print(v)
total = np.sum(v)
total

[ 0  2  4  6  8 10 12 14 16 18 20]


np.int64(110)

## 2. Arreglos multidimensionales (2D/3D)
**Objetivo:** crear matrices y tensores, y comprender `shape`/`ndim`.

**Ejercicio 2.1** → Crea una matriz `B` de tamaño 2×3 con los números del 1 al 6 usando `np.array` con listas anidadas.

In [ ]:
# Tu código aquí
B = np.array([[1, 2, 3],
             [4, 5, 6]])

B, B.shape, B.ndim


(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 2)

**Ejercicio 2.2** → Crea un arreglo 3D de forma `(2, 2, 3)` con valores del 0 al 11 usando `np.arange` y `reshape`.

In [13]:
# Tu código aquí
C = np.arange(12).reshape(2, 2, 3)
C, C.shape, C.ndim


(array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]),
 (2, 2, 3),
 3)

## 3. Propiedades del arreglo
**Objetivo:** trabajar con `dtype`, `size`, `itemsize`, `nbytes`.

**Ejercicio 3.1** → Convierte el vector `a` del Ej. 1.1 a tipo `float64` y comprueba `dtype`, `itemsize` y `nbytes`.

In [16]:
# Tu código aquí
a_float = a.astype(np.float64)
a_float.dtype, a_float.itemsize, a_float.nbytes


(dtype('float64'), 8, 40)

**Ejercicio 3.2** → Crea un arreglo de 1000 enteros y compara su `nbytes` con el mismo arreglo en `float32` y `float64`.

In [18]:
# Tu código aquí
arr_int = np.arange(1000)
arr_f32 = arr_int.astype(np.float32)
arr_f64 = arr_int.astype(np.float64)

arr_int.nbytes, arr_f32.nbytes, arr_f64.nbytes

(8000, 4000, 8000)

## 4. Operaciones básicas y estadísticas
**Objetivo:** practicar suma, multiplicación, `mean`, `std`, `min`, `max`.

**Ejercicio 4.1** → Dados `x = [1, 2, 3]` y `y = [4, 5, 6]`, calcula `x + y`, `x * y` y `x ** 2`.

In [21]:
# Tu código aquí
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x+y)
print(x*y)
print(x**2)


[5 7 9]
[ 4 10 18]
[1 4 9]


**Ejercicio 4.2** → Para `d = [2, 4, 6, 8]`, calcula `mean`, `std`, `min`, `max`.

In [24]:
# Tu código aquí
d = [2, 4, 6, 8]

print(np.mean(d))
print(np.std(d))
print(np.min(d))
print(np.max(d))

5.0
2.23606797749979
2
8


## 5. Reorganización (`reshape`) y aplanamiento (`flatten`)

**Ejercicio 5.1** → Crea un vector del 0 al 11 y **reorganízalo** a una matriz de forma `(3, 4)`.

In [25]:
# Tu código aquí
v = np.arange(12)
M = v.reshape(3, 4)
M, M.shape


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

**Ejercicio 5.2** → Aplana la matriz `M` del ejercicio anterior a un vector 1D usando `flatten` y `ravel`. ¿Qué diferencias observas?

In [26]:
# Tu código aquí
v_flatten = M.flatten()
v_ravel = M.ravel()

print("M:\n", M)
print("\nflatten:", v_flatten)
print("ravel  :", v_ravel)


M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel  : [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 6. Indexación y slicing

**Ejercicio 6.1** → Dada la matriz `A = [[10, 20, 30],[40, 50, 60]]`, extrae: (a) el elemento 50, (b) la primera fila, (c) la tercera columna.

In [28]:
# Tu código aquí
A = np.array([[10, 20, 30],
              [40, 50, 60]])

# elemento 50 -> fila 1, columna 1
el_50 = A[1,1]

# primera finally
fila_1 = A[0, :]

# 3ra columna
col_3 = A[:, 2]

print("(a) elemento 50:", el_50)
print("(b) primera fila:", fila_1)
print("(c) tercera columna:", col_3)



(a) elemento 50: 50
(b) primera fila: [10 20 30]
(c) tercera columna: [30 60]


**Ejercicio 6.2** → Usando slicing sobre `np.arange(20)`, obtén los elementos en posiciones pares (índices 0,2,4,...) y los últimos 5 elementos.

In [29]:
# Tu código aquí
v = np.arange(20)
pares = v[::2]
ult_5 = v[-5:]

print("Vector original:", v)
print("Posiciones pares:", pares)
print("Últimos 5 elementos:", ult_5)


Vector original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Posiciones pares: [ 0  2  4  6  8 10 12 14 16 18]
Últimos 5 elementos: [15 16 17 18 19]
